##  Dataset and Dataloader Implementation

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X, y = make_classification(

  n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [3]:
X = torch.from_numpy(X).float()
y = torch.from_numpy(y).long()
X,y

(tensor([[ 1.0683, -0.9701],
         [-1.1402, -0.8388],
         [-2.8954,  1.9769],
         [-0.7206, -0.9606],
         [-1.9629, -0.9923],
         [-0.9382, -0.5430],
         [ 1.7273, -1.1858],
         [ 1.7774,  1.5116],
         [ 1.8997,  0.8344],
         [-0.5872, -1.9717]]),
 tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

### Dataset Class

In [ ]:
from torch.utils.data import Dataset,DataLoader
class customDataset(Dataset):
    def __init__(self,X,y):
        self.features = X
        self.labels = y
    
    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self,index):
        #this tells how the data should be accessed.
        #here it quite simple because data is already stored in array.
        return self.features[index], self.labels[index]

In [5]:
dataset = customDataset(X,y)

### Child of DataLoader to help us loading the data only when required.

In [ ]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True) 

In [12]:
for batch_feautures,batch_size in dataloader:
    print(batch_feautures)
    print(batch_size)
    print('**********')

tensor([[-1.1402, -0.8388],
        [-0.7206, -0.9606]])
tensor([0, 0])
**********
tensor([[ 1.7273, -1.1858],
        [-2.8954,  1.9769]])
tensor([1, 0])
**********
tensor([[-0.5872, -1.9717],
        [-0.9382, -0.5430]])
tensor([0, 1])
**********
tensor([[-1.9629, -0.9923],
        [ 1.0683, -0.9701]])
tensor([0, 1])
**********
tensor([[1.8997, 0.8344],
        [1.7774, 1.5116]])
tensor([1, 1])
**********
