# NN module Pipeline

In [1]:
import torch
import torch.nn as nn

In [10]:
class SimpleNetwork(nn.Module):
    #Defining the architecture of the network
    def __init__(self, no_features):
        super().__init__()
        self.linear = nn.Linear(no_features,1)
        self.activation = nn.Sigmoid()

    #Defining the forward pass
    def forward(self,features):
        out = self.linear(features)
        out = self.activation(out)
        return out

In [4]:
dataset = torch.rand(10,5)

In [11]:
model = SimpleNetwork(dataset.shape[1])
model(dataset)

tensor([[0.5432],
        [0.5552],
        [0.5493],
        [0.5370],
        [0.5472],
        [0.5300],
        [0.5349],
        [0.5296],
        [0.5007],
        [0.5277]], grad_fn=<SigmoidBackward0>)

## Creating the NN with a single hidden layer

In [15]:
class HiddenLayeredNN(nn.Module):
    def __init__(self,no_of_feautures):
        super().__init__()
        self.layer1 = nn.Linear(no_of_feautures,3)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,X_data):
        output = self.layer1(X_data)
        output = self.relu(output)
        output = self.layer2(output)
        output = self.sigmoid(output)
        return output

In [16]:
model = HiddenLayeredNN(5)
model(dataset)

tensor([[0.5889],
        [0.6114],
        [0.5923],
        [0.6063],
        [0.5889],
        [0.5753],
        [0.5561],
        [0.6228],
        [0.5815],
        [0.5855]], grad_fn=<SigmoidBackward0>)

## Sequential Container

In [17]:
class model(nn.Module):
    def __init__(self,no_of_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(no_of_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,data):
        output = self.network(data)
        return output


In [18]:
no_of_features = 5
mymodel = model(5)
mymodel(dataset)

tensor([[0.4135],
        [0.4084],
        [0.4409],
        [0.4349],
        [0.4247],
        [0.4618],
        [0.4319],
        [0.4142],
        [0.4371],
        [0.4174]], grad_fn=<SigmoidBackward0>)