In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [5]:
#Creating a separate a Class
class FeedForwardNet(nn.Module): #Inherits from the Torch module
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(2,5)
        self.sigmoid = nn.Sigmoid()   #Two inputs neuron to 5 hidden neuron 
        self.layer2 = nn.Linear(5,1)   #5 Hidden neuron  to 1 output.
    
    def forward(self, input):
        x = self.layer1(input)
        x = self.sigmoid(x)
        #Input data is supplied to the first layer which is acted by the activation function
        #self.layer1(input) will do linear operation z = wx+b later sigmoid is applied on this make it non-linear
        x = self.layer2(x)
        x = self.sigmoid(x) 
        return x

In [6]:
#Considering the inputs and outputs
X = torch.tensor([[0,0],[0,1],[1,0],[0,1],[1,0],[1,1],[1,0],[1,1],[0,1],[0,0],[0,0],[1,1],[0,1],[0,1],[1,1]],dtype = torch.float32)

y = torch.tensor([[0],[1],[1],[1],[1],[0],[1],[0],[1],[0],[0],[0],[1],[1],[0],], dtype=torch.float32)


In [7]:
model = FeedForwardNet()
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)


In [8]:
#Training 
for epoch in range(1000):
    outputs = model(X)
    loss = criterion(outputs,y)
    optimizer.zero_grad()

    loss.backward()
    optimizer.step()

    if (epoch+1) %10 == 0:
        print(f'Epoch of {epoch},loss:{loss.item():.4f}')
    


Epoch of 9,loss:0.6771
Epoch of 19,loss:0.6091
Epoch of 29,loss:0.4656
Epoch of 39,loss:0.3742
Epoch of 49,loss:0.2783
Epoch of 59,loss:0.1549
Epoch of 69,loss:0.0782
Epoch of 79,loss:0.0439
Epoch of 89,loss:0.0286
Epoch of 99,loss:0.0210
Epoch of 109,loss:0.0166
Epoch of 119,loss:0.0138
Epoch of 129,loss:0.0119
Epoch of 139,loss:0.0104
Epoch of 149,loss:0.0092
Epoch of 159,loss:0.0083
Epoch of 169,loss:0.0075
Epoch of 179,loss:0.0068
Epoch of 189,loss:0.0062
Epoch of 199,loss:0.0057
Epoch of 209,loss:0.0053
Epoch of 219,loss:0.0049
Epoch of 229,loss:0.0046
Epoch of 239,loss:0.0043
Epoch of 249,loss:0.0040
Epoch of 259,loss:0.0038
Epoch of 269,loss:0.0036
Epoch of 279,loss:0.0034
Epoch of 289,loss:0.0032
Epoch of 299,loss:0.0030
Epoch of 309,loss:0.0029
Epoch of 319,loss:0.0027
Epoch of 329,loss:0.0026
Epoch of 339,loss:0.0025
Epoch of 349,loss:0.0024
Epoch of 359,loss:0.0023
Epoch of 369,loss:0.0022
Epoch of 379,loss:0.0021
Epoch of 389,loss:0.0020
Epoch of 399,loss:0.0019
Epoch of 40

In [9]:
X_test = torch.tensor([[1,1],[1,0],[1,1],[0,0],[0,1]], dtype = torch.float32)

y_test = torch.tensor([[0],[1],[0],[0],[1]],dtype = torch.float32)

In [10]:
model.eval()
with torch.no_grad():
    predicted = model(X_test)
    loss = criterion(predicted,y_test)
    print('Error on Test Data',loss.item())

Error on Test Data 0.0005512469215318561


In [11]:
print(predicted)

tensor([[8.3810e-04],
        [9.9902e-01],
        [8.3810e-04],
        [3.0278e-05],
        [9.9993e-01]])


In [12]:
print(y_test,predicted)

tensor([[0.],
        [1.],
        [0.],
        [0.],
        [1.]]) tensor([[8.3810e-04],
        [9.9902e-01],
        [8.3810e-04],
        [3.0278e-05],
        [9.9993e-01]])


In [13]:
import pandas as pd
import numpy as np

In [16]:
data = torch.cat((X_test,y_test,predicted), dim = 1).numpy()
data

array([[1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 8.3810359e-04],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 9.9902141e-01],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 8.3810359e-04],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.0277799e-05],
       [0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 9.9993002e-01]],
      dtype=float32)

In [17]:
df = pd.DataFrame(data, columns = ['Test Input 1','Test Input 2','Target Values','Predicted Values'])

In [18]:
df

Test Input 1  Test Input 2  Target Values  Predicted Values
0           1.0           1.0            0.0          0.000838
1           1.0           0.0            1.0          0.999021
2           1.0           1.0            0.0          0.000838
3           0.0           0.0            0.0          0.000030
4           0.0           1.0            1.0          0.999930