In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [15]:
#Creating a separate a Class
class FeedForwardNet(nn.Module): #Inherits from the Torch module
    def __init__(self):
        super(FeedForwardNet,self).__init__()
        self.layer1 = nn.Linear(2,5)   #Two inputs neuron to 5 hidden neuron 
        self.layer2 = nn.Linear(5,1)   #5 Hidden neuron  to 1 output.
    
    def forward(self, input):
        x = torch.sigmoid(self.layer1(input))
        #Input data is supplied to the first layer which is acted by the activation function
        #self.layer1(input) will do linear operation z = wx+b later sigmoid is applied on this make it non-linear
        x = torch.sigmoid(self.layer2(x)) 
        return x

In [16]:
#Considering the inputs and outputs
X = torch.tensor([[0,0],[0,1],[1,0],[0,1],[1,0],[1,1],[1,0],[1,1],[0,1],[0,0],[0,0],[1,1],[0,1],[0,1],[1,1]],dtype = torch.float32)

y = torch.tensor([[0],[1],[1],[1],[1],[0],[1],[0],[1],[0],[0],[0],[1],[1],[0],], dtype=torch.float32)


In [17]:
model = FeedForwardNet()
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)


In [40]:
#Training 
for epoch in range(1000):
    outputs = model(X)
    loss = criterion(outputs,y)
    optimizer.zero_grad()

    loss.backward()
    optimizer.step()

    if (epoch+1) %10 == 0:
        print(f'Epoch of {epoch},loss:{loss.item():.4f}')
    


Epoch of 9,loss:0.0001
Epoch of 19,loss:0.0001
Epoch of 29,loss:0.0001
Epoch of 39,loss:0.0001
Epoch of 49,loss:0.0001
Epoch of 59,loss:0.0001
Epoch of 69,loss:0.0001
Epoch of 79,loss:0.0001
Epoch of 89,loss:0.0001
Epoch of 99,loss:0.0001
Epoch of 109,loss:0.0001
Epoch of 119,loss:0.0001
Epoch of 129,loss:0.0001
Epoch of 139,loss:0.0001
Epoch of 149,loss:0.0001
Epoch of 159,loss:0.0001
Epoch of 169,loss:0.0001
Epoch of 179,loss:0.0001
Epoch of 189,loss:0.0001
Epoch of 199,loss:0.0001
Epoch of 209,loss:0.0001
Epoch of 219,loss:0.0001
Epoch of 229,loss:0.0001
Epoch of 239,loss:0.0001
Epoch of 249,loss:0.0001
Epoch of 259,loss:0.0000
Epoch of 269,loss:0.0000
Epoch of 279,loss:0.0000
Epoch of 289,loss:0.0000
Epoch of 299,loss:0.0000
Epoch of 309,loss:0.0000
Epoch of 319,loss:0.0000
Epoch of 329,loss:0.0000
Epoch of 339,loss:0.0000
Epoch of 349,loss:0.0000
Epoch of 359,loss:0.0000
Epoch of 369,loss:0.0000
Epoch of 379,loss:0.0000
Epoch of 389,loss:0.0000
Epoch of 399,loss:0.0000
Epoch of 40

In [41]:
X_test = torch.tensor([[1,1],[1,0],[1,1],[0,0],[0,1]], dtype = torch.float32)

y_test = torch.tensor([[0],[1],[0],[0],[1]],dtype = torch.float32)

In [42]:
model.eval()
with torch.no_grad():
    predicted = model(X_test)
    loss = criterion(predicted,y_test)
    print('Error on Test Data',loss.item())

Error on Test Data 3.0106686608633026e-05


In [43]:
print(predicted)

tensor([[3.7519e-05],
        [9.9996e-01],
        [3.7519e-05],
        [1.1955e-05],
        [9.9998e-01]])


In [44]:
print(y_test,predicted)

tensor([[0.],
        [1.],
        [0.],
        [0.],
        [1.]]) tensor([[3.7519e-05],
        [9.9996e-01],
        [3.7519e-05],
        [1.1955e-05],
        [9.9998e-01]])


In [45]:
import pandas as pd
import numpy as np

In [46]:
data = torch.cat((X_eval,y_eval,predicted), dim = 1).numpy()
data

array([[1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.7518548e-05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 9.9996090e-01],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 3.7518548e-05],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.1955243e-05],
       [0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 9.9997556e-01]],
      dtype=float32)

In [47]:
df = pd.DataFrame(data, columns = ['Test Input 1','Test Input 2','Target Values','Predicted Values'])

In [48]:
df

Test Input 1  Test Input 2  Target Values  Predicted Values
0           1.0           1.0            0.0          0.000038
1           1.0           0.0            1.0          0.999961
2           1.0           1.0            0.0          0.000038
3           0.0           0.0            0.0          0.000012
4           0.0           1.0            1.0          0.999976